apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Pankajsh947/argocd-poc.git
    path: Charts/hello-world
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
