apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: 058264270539.dkr.ecr.us-east-1.amazonaws.com/argocd-test-app:0.1
        name: demo-app
        ports:
        - containerPort: 80
