apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-appprojects
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: argocd-channel
spec:
  project: argocd
  source:
    repoURL: https://github.com/Pankajsh947/argocd-poc.git
    path: argocd-appprojects
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
