apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-applicationset-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - cluster: https://339366CE694DE472810E7D0613DDC26A.gr7.us-east-1.eks.amazonaws.com
            path: app1
          - cluster:  https://kubernetes.default.svc
            path: app2
  template:
    metadata:
      name: '{{path}}-application'

    spec:
      project: development
      source:
        repoURL: https://github.com/Pankajsh947/argocd-poc.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{cluster}}'
        namespace: demoapp
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
