apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: 058264270539.dkr.ecr.us-east-1.amazonaws.com/argocd-test-app
    argocd-image-updater.argoproj.io/argocd-test-app.update-strategy: latest
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: argocd-channel
spec:
  project: development
  source:
    repoURL: https://github.com/Pankajsh947/argocd-poc.git
    path: Charts/hello-world
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
