apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: argocd-channel
spec:
  project: default
  source:
    repoURL: https://github.com/Pankajsh947/argocd-poc.git
    path: sample-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: guestbook-ui
    jqPathExpressions:
      - .spec.template.spec.containers[0].image
